import { OutputFormatter } from './formatter-interface.js';
import { ScanResult, getScanSummary } from '../core/models/scan-result.js';
import { Finding } from '../core/models/finding.js';
import { Severity, severityOrder } from '../core/models/severity.js';
import { formatSourceLocation } from '../core/models/source-location.js';

export class MarkdownFormatter implements OutputFormatter {
  readonly name = 'markdown';

  format(result: ScanResult): string {
    const lines: string[] = [];
    const summary = getScanSummary(result);

    // Title
    lines.push('# ApiPosture Security Scan Report');
    lines.push('');

    // Scan Info
    lines.push('## Scan Information');
    lines.push('');
    lines.push(`| Property | Value |`);
    lines.push(`|----------|-------|`);
    lines.push(`| Project | \`${result.projectPath}\` |`);
    lines.push(`| Scan Date | ${result.scanDate.toISOString()} |`);
    lines.push(`| Files Scanned | ${result.filesScanned} |`);
    lines.push(`| Endpoints Found | ${summary.totalEndpoints} |`);
    lines.push(`| Scan Duration | ${result.scanDurationMs}ms |`);
    lines.push('');

    // Summary
    lines.push('## Summary');
    lines.push('');

    if (summary.totalFindings === 0) {
      lines.push('**No security findings detected.**');
    } else {
      lines.push(`**Total Findings:** ${summary.totalFindings}`);
      lines.push('');
      lines.push('| Severity | Count |');
      lines.push('|----------|-------|');

      for (const severity of Object.values(Severity).reverse()) {
        const count = summary.findingsBySeverity[severity];
        if (count > 0) {
          const badge = this.getSeverityBadge(severity);
          lines.push(`| ${badge} ${severity} | ${count} |`);
        }
      }
    }

    lines.push('');

    // Findings
    if (summary.totalFindings > 0) {
      lines.push('## Findings');
      lines.push('');

      const activeFindings = result.findings.filter((f) => !f.suppressed);
      const sortedFindings = this.sortFindingsBySeverity(activeFindings);

      for (const finding of sortedFindings) {
        lines.push(this.formatFinding(finding));
      }
    }

    // Endpoints Table
    lines.push('## Endpoints');
    lines.push('');
    lines.push('| Method | Route | Classification | Framework | Location |');
    lines.push('|--------|-------|----------------|-----------|----------|');

    for (const endpoint of result.endpoints) {
      lines.push(
        `| ${endpoint.method} | \`${endpoint.route}\` | ${endpoint.authorization.classification} | ${endpoint.type} | ${endpoint.location.filePath}:${endpoint.location.line} |`
      );
    }

    lines.push('');

    // Suppressed
    if (summary.suppressedFindings > 0) {
      lines.push('## Suppressed Findings');
      lines.push('');
      lines.push(`${summary.suppressedFindings} findings were suppressed.`);
      lines.push('');
    }

    // Footer
    lines.push('---');
    lines.push('*Generated by ApiPosture*');
    lines.push('');

    return lines.join('\n');
  }

  private formatFinding(finding: Finding): string {
    const lines: string[] = [];
    const badge = this.getSeverityBadge(finding.severity);

    lines.push(`### ${badge} ${finding.ruleId}: ${finding.ruleName}`);
    lines.push('');
    lines.push(`**Severity:** ${finding.severity}`);
    lines.push('');
    lines.push(`**Endpoint:** \`${finding.endpoint.method} ${finding.endpoint.route}\``);
    lines.push('');
    lines.push(`**Location:** \`${formatSourceLocation(finding.location)}\``);
    lines.push('');
    lines.push(`**Message:** ${finding.message}`);
    lines.push('');
    lines.push('**Recommendation:**');
    lines.push('');
    lines.push(`> ${finding.recommendation}`);
    lines.push('');

    return lines.join('\n');
  }

  private getSeverityBadge(severity: Severity): string {
    switch (severity) {
      case Severity.Critical:
        return '\ud83d\udfe5';
      case Severity.High:
        return '\ud83d\udd34';
      case Severity.Medium:
        return '\ud83d\udfe0';
      case Severity.Low:
        return '\ud83d\udfe1';
      case Severity.Info:
        return '\ud83d\udfe2';
      default:
        return '\u26aa';
    }
  }

  private sortFindingsBySeverity(findings: Finding[]): Finding[] {
    return [...findings].sort(
      (a, b) => severityOrder[b.severity] - severityOrder[a.severity]
    );
  }
}
